TRAIN:
    LEARNING_RATE: 2.0e-5
    WEIGHT_DECAY: 1.0e-2
    EPSILON: 1.0e-8
    EPOCHS: 20
    TARGET_PATH: "./data/real_train_data.pickle" 
    #SUPPORT_PATH: ["./data/fake_train_data.pickle"]
    SUPPORT_PATH: ["./data/gpt2_data.pickle", "./data/fake_train_data.pickle"] #use augmentation method


TEST:
    TARGET_PATH: "./data/real_test_data.pickle" 
    SUPPORT_PATH: ["./data/fake_test_data.pickle"]
